algoritmo "intervalo"
var
  num: inteiro
inicio

      Escreval("Algoritmo que verifica o intervalo entre os números 100 à 1000")
      Escreval("")
      
      Escreval("Digite o número para a verificação: ")
      Leia(num)
      
      Se (num >= 100) e (num <= 1000) Entao
         Escreval("O número digitado está no intervalo entre 100 e 1000")
      Senao
           Escreval("O número digitado não está no intervalo entre 100 e 1000")
      FimSe
fimalgoritmo
